In [4]:
import pandas as pd

In [5]:
copacabana = pd.read_csv('copacabana.csv', delimiter=';')

In [7]:
copacabana.columns

Index(['Posicao', 'Quartos', 'Vagas', 'DistIpanema', 'DistPraia', 'DistFavela',
       'RendaMedia', 'RendaMovel', 'RendaMovelRua', 'Vu2009', 'Mes', 'Idade',
       'Tipologia', 'AreaConstruida', 'VAL_UNIT', 'X', 'Y'],
      dtype='object')

In [9]:
copacabana['Quartos'].describe()

count    1675.000000
mean        1.767510
std         1.142523
min         0.010000
25%         1.000000
50%         2.000000
75%         3.000000
max         6.000000
Name: Quartos, dtype: float64

In [11]:
copacabana['Quartos'] > 5

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
1645    False
1646    False
1647    False
1648    False
1649    False
1650    False
1651    False
1652    False
1653    False
1654    False
1655    False
1656    False
1657    False
1658    False
1659    False
1660    False
1661    False
1662    False
1663    False
1664    False
1665    False
1666    False
1667    False
1668    False
1669    False
1670    False
1671    False
1672    False
1673    False
1674    False
Name: Quartos, Length: 1675, dtype: bool

In [15]:
copacabana.loc[copacabana['Quartos'] == 6]

,Posicao,Quartos,Vagas,DistIpanema,DistPraia,DistFavela,RendaMedia,RendaMovel,RendaMovelRua,Vu2009,Mes,Idade,Tipologia,AreaConstruida,VAL_UNIT,X,Y
748,1,6.0,2.0,2500,35,743,1524600,1275377,1399989,4100,360,58.0,1,668,4491,686456.25,7458801.05

In [17]:
copacabana.loc[copacabana['Quartos'] == 5]

,Posicao,Quartos,Vagas,DistIpanema,DistPraia,DistFavela,RendaMedia,RendaMovel,RendaMovelRua,Vu2009,Mes,Idade,Tipologia,AreaConstruida,VAL_UNIT,X,Y
173,1,5.0,0.01,2696,154,712,1083455,649733,866594,2000,425,55.0,1,38,6316,686522.9800,7458989.87
1521,1,5.0,3.00,3044,31,609,1524600,1168222,1346411,4100,405,34.0,1,430,5000,686965.3201,7459109.71

In [22]:
copacabana.loc[copacabana['Quartos'] == 4]

,Posicao,Quartos,Vagas,DistIpanema,DistPraia,DistFavela,RendaMedia,RendaMovel,RendaMovelRua,Vu2009,Mes,Idade,Tipologia,AreaConstruida,VAL_UNIT,X,Y
86,1,4.0,0.01,1582,72,606,1203742,742088,972915,2900,573,57.0,1,177,6780,685768.5229,7458130.424
132,1,4.0,1.00,2254,393,437,1165764,1174193,1169979,2200,484,57.0,1,259,3282,685888.3500,7458805.170
168,1,4.0,1.00,2232,453,428,1156319,1020660,1088490,2600,445,55.0,1,303,3960,685806.9201,7458809.640
178,1,4.0,1.00,480,282,420,1570125,1616109,1593117,2500,904,56.0,1,281,10872,685329.6134,7457118.830
180,1,4.0,1.00,2070,34,770,1524600,1231443,1378022,4100,800,55.0,1,500,10486,686101.2900,7458510.880
188,1,4.0,1.00,470,323,386,1566345,1295855,1431100,2700,405,53.0,1,316,3006,685286.4300,7457125.600
189,1,4.0,1.00,470,323,386,1566345,1295855,1431100,2700,595,53.0,1,316,6329,685286.4300,7457125.600
190,1,4.0,1.00,1332,244,333,1476163,1214419,1345291,2450,864,56.0,1,296,11149,685494.3200,7457964.580
191,1,4.0,1.00,1305,241,306,1476163,1214419,1345291,2450,405,52.0,1,252,2976,685487.2900,7457938.720
196,1,4.0,1.00,2263,50,698,986211,981554,983883,2500,573,70.0,1,335,5672,686236.8800,7458655.710
197,1,4.0,0.01,2631,32,806,1524600,1707651,1616126,4100,864,73.0,1,197,13706,686577.2000,7458879.630
198,1,4.0,1.00,1496,323,396,1221509,914508,1068009,2500,445,52.0,1,238,3571,685485.3700,7458136.010
199,1,4.0,1.00,579,141,403,1570125,1699355,1634740,2500,385,52.0,1,184,3832,685466.0100,7457153.440
209,1,4.0,1.00,2390,78,669,1194735,1015488,1105112,2800,842,53.0,1,328,6555,686317.4100,7458756.380
210,1,4.0,1.00,2390,78,669,1194735,1015488,1105112,2800,567,50.0,1,328,6707,686317.4100,7458756.380
211,1,4.0,1.00,2390,78,669,1194735,1015488,1105112,2800,930,53.0,1,328,8049,686317.4100,7458756.380
212,1,4.0,1.00,2390,78,669,1194735,1015488,1105112,2800,405,50.0,1,328,3963,686317.4100,7458756.380
213,1,4.0,0.01,449,337,386,1570125,1458348,1514237,2500,405,50.0,1,280,5000,685276.0717,7457107.035
241,0,4.0,1.00,1717,560,226,1496791,1247006,1371899,2500,405,53.0,1,113,4248,685353.4801,7458386.220
244,1,4.0,1.00,499,253,415,1570125,1466775,1518450,2500,842,55.0,1,179,11173,685356.9600,7457126.700
254,1,4.0,1.00,2330,537,322,1472861,1637545,1555203,2300,445,52.0,1,258,4651,685795.3000,7458915.920
314,1,4.0,1.00,3201,31,443,1524600,1189176,1356888,4100,445,52.0,1,191,6806,687120.1000,7459188.460
442,1,4.0,1.00,754,203,165,1215942,1310446,1263194,2450,792,51.0,1,200,9000,685388.1900,7457390.860
446,1,4.0,1.00,1786,576,268,1207360,1447135,1327248,2500,842,53.0,1,215,6977,685372.6600,7458452.810
450,1,4.0,1.00,1136,74,191,1315094,1102680,1208887,2700,830,51.0,1,158,12658,685588.2001,7457721.810
471,1,4.0,2.00,807,34,233,1524600,894300,1209450,4100,862,50.0,1,344,18023,685555.9700,7457367.330
560,1,4.0,1.00,363,271,583,1404545,1711526,1558036,2600,930,50.0,1,210,11905,685392.0600,7456931.400
582,1,4.0,1.00,640,35,448,1524600,1523182,1523891,4100,920,72.0,1,200,15750,685579.2700,7457136.750
590,1,4.0,1.00,1674,267,500,1207360,1204380,1205870,2500,509,65.0,1,194,6186,685631.9300,7458280.390
592,1,4.0,0.01,1200,94,234,1189386,1211957,1200672,2500,425,66.0,1,166,5120,685590.0500,7457791.450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,0,4.0,0.01,658,382,182,1215942,1126165,1171054,2350,405,53.0,1,155,4774,685207.5100,7457337.070
987,1,4.0,1.00,1488,80,510,1259839,1159289,1209564,2900,360,54.0,1,300,3167,685715.1800,7458050.290
1018,1,4.0,1.00,1640,401,348,1124331,1228204,1176268,2200,425,54.0,1,230,2283,685478.9900,7458286.240
1060,1,4.0,1.00,1495,548,181,1496791,2063441,1780116,2500,425,53.0,1,180,5278,685254.3400,7458174.020
1148,1,4.0,1.00,2254,635,365,1395924,1797685,1596805,1550,567,53.0,1,196,5102,685626.5500,7458882.090
1149,0,4.0,0.01,2254,635,365,1395924,1797685,1596805,1550,525,53.0,1,196,4439,685626.5500,7458882.090
1192,1,4.0,1.00,436,400,328,1532655,1378767,1455711,2600,445,47.0,1,265,3472,685210.1800,7457112.090
1197,1,4.0,1.00,647,411,189,1215942,1175438,1195690,2350,484,46.0,1,277,3610,685178.2500,7457328.710
1198,1,4.0,1.00,422,214,588,1308645,1494017,1401331,2100,405,44.0,1,222,3514,685441.5000,7456965.640
1214,1,4.0,1.00,460,190,548,1308645,1455122,1381884,2100,830,47.0,1,179,10615,685454.6001,7457007.030
1226,1,4.0,1.00,1549,34,582,1524600,906916,1215758,4100,525,47.0,1,274,5839,685787.0200,7458084.900
1300,1,4.0,1.00,601,80,447,1083455,1631774,1357615,2200,425,67.0,1,270,2778,685536.9800,7457122.910
1341,1,4.0,0.01,1277,36,326,1524600,988624,1256612,4100,509,43.0,1,224,7143,685667.6700,7457840.790
1367,1,4.0,2.00,898,34,173,1524600,1319327,1421964,4100,525,40.0,1,362,6630,685566.3100,7457466.820
1379,1,4.0,2.00,3077,525,564,1573665,1638923,1606294,2600,920,44.0,1,250,7880,686521.3639,7459426.649
1380,1,4.0,3.00,3077,525,564,1573665,1638923,1606294,2600,509,41.0,1,250,3440,686521.3639,7459426.649
1386,1,4.0,1.00,2554,476,271,1472861,1211386,1342124,2300,554,42.0,1,235,3830,686060.4200,7459061.610
1408,0,4.0,0.01,1371,172,376,1083455,1051056,1067256,2200,425,62.0,1,155,3329,685577.7700,7457978.520
1421,1,4.0,2.00,1919,470,486,1369604,1411642,1390623,2600,573,42.0,1,292,5171,685566.3316,7458552.459
1466,1,4.0,2.00,2898,144,810,1083455,1352142,1217799,2000,567,67.0,1,126,7143,686723.3081,7459102.814
1522,1,4.0,4.00,3044,31,609,1524600,1168222,1346411,4100,573,34.0,1,395,7595,686965.3201,7459109.710
1550,0,4.0,3.00,944,40,155,1524600,1370221,1447411,4100,425,30.0,1,192,4583,685568.3900,7457518.610
1551,1,4.0,4.00,944,40,155,1524600,1370221,1447411,4100,484,30.0,1,205,10732,685568.3900,7457518.610
1552,0,4.0,3.00,944,40,155,1524600,1370221,1447411,4100,509,30.0,1,192,5208,685568.3900,7457518.610
1572,1,4.0,3.00,2375,93,651,1194735,1490245,1342490,2800,525,30.0,1,243,6502,686289.9200,7458754.630
1576,1,4.0,3.00,3008,545,545,1697312,1990088,1843700,2400,484,30.0,1,188,2926,686430.8300,7459394.470
1582,0,4.0,2.00,3074,577,510,1573665,1556859,1565262,2600,573,27.0,1,97,8041,686463.1000,7459452.070
1598,1,4.0,3.00,765,184,158,1215942,1270336,1243139,2450,792,27.0,1,182,6593,685407.1200,7457395.900
1599,1,4.0,1.00,745,436,92,1159555,974669,1067112,990,484,27.0,1,202,2624,685156.3700,7457428.260
1654,0,4.0,3.00,2442,894,189,1783469,1696269,1739869,2300,920,12.0,1,166,13253,685475.4576,7459100.927

In [23]:
copacabana['AreaConstruida'] * copacabana['VAL_UNIT']

0        416005
1        460009
2        720012
3        990000
4        909976
5        790024
6        670015
7        249990
8        319990
9        299997
10       390000
11       299992
12       410000
13       749990
14       625022
15       619972
16       309986
17       340032
18       760000
19       870020
20       250005
21       340005
22       210000
23       139995
24       270000
25        90000
26       350010
27       450022
28       329975
29       210033
         ...
1645     792984
1646    1393956
1647     810027
1648    1800022
1649     886990
1650     969992
1651     499968
1652     560032
1653     284984
1654    2199998
1655    2179944
1656     300011
1657     180000
1658     280016
1659     229992
1660     342012
1661     699996
1662     710024
1663    1320000
1664     300024
1665     700024
1666     390000
1667     434980
1668     219996
1669     639975
1670     479940
1671     402040
1672     600020
1673     766705
1674     683871
Length: 1675, dtype: int64

In [24]:
copacabana['TOTAL'] = copacabana['AreaConstruida'] * copacabana['VAL_UNIT']

In [26]:
copacabana['TOTAL'].describe()

count    1.675000e+03
mean     5.862613e+05
std      4.804788e+05
min      6.000000e+04
25%      3.000000e+05
50%      4.500320e+05
75%      7.200115e+05
max      6.199912e+06
Name: TOTAL, dtype: float64

In [28]:
copacabana['TOTAL'].head()

0    416005
1    460009
2    720012
3    990000
4    909976
Name: TOTAL, dtype: int64

In [29]:
copacabana['TOTAL'].tail()

1670    479940
1671    402040
1672    600020
1673    766705
1674    683871
Name: TOTAL, dtype: int64